# Generated by Django 4.2 on 2023-05-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('classs', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
